name: carebellmom
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  group_button: ^5.3.4
  flutter_image_slideshow: ^0.1.6
  curved_navigation_bar: ^1.0.6
  animated_notch_bottom_bar: ^1.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/login_page/
    - assets/intro_page/
    - assets/index_page/
    - assets/jk/